[project]
name = "cispa-hackathon"
version = "0.1.0"
description = "AI & Cybersecurity CISPA Hackathon 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
